require('./components/MainComponent.jsx')
require('./style/style.scss')
require('./js/main.js')
require('./assets/img/unknowpleasures.jpeg')
require('./assets/cv.pdf')
require('./assets/favicon.ico')
